### PR TITLE
Add gcc-5.1 Dockerfile to create Docker image to test ITK

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Comment by fbudin69500** [comment]
This is a follow up of the discussion [here](https://github.com/InsightSoftwareConsortium/ITKCIDeployment/issues/2).

**Comment by fbudin69500** [comment]
Before merging this, I want to make sure that this is the correct path. I just discovered [module-ci](https://github.com/InsightSoftwareConsortium/ITKDevelopmentEnvironment/tree/master/Docker/module-ci) which should also probably moved here. What do you think?

**Comment by fbudin69500** [comment]
Superseded by #4

**Comment by thewtex** [comment]
+1 for moving `module-ci.`.

**Pull request closed without merging**
